### ISSUE TITLE
Trying to compile the main file

### ISSUE THREAD

**Issue by shanejamrock** [Wilfred/babyc#2]
hey man, i must say you have done a great work with this. And i will put in the credits. 
However im having an issue.. when i try to compile the main.c file 
$gcc main.c -o a.out
i get the following error : 
main.c:9:25: fatal error: build/y.tab.h: No such file or directory
compilation terminated

Any help please. Urgent

**Comment by Wilfred** [comment]
Hi there!

You just need to call `make` to compile babyc. This is in the readme, let me know if the readme is missing anything.

**Comment by shanejamrock** [comment]
I did run make. But I got an error...I'll send it to u shortly the error.
On Apr 9, 2015 2:54 AM, Wilfred Hughes notifications@github.com wrote:Closed #2.

**Comment by shanejamrock** [comment]
ok this is the error i got when i ran make
: 
yacc -d babyc_parse.y -o build/y.tab.c
conflicts: 12 shift/reduce
lex -t babyc_lex.l > build/lex.yy.c
/bin/sh: 1: lex: not found
make: **\* [build/lex.yy.c] Error 127

**Comment by Wilfred** [comment]
> lex: not found

You need lex installed. I've added a note in the README about this.

**Comment by shanejamrock** [comment]
Isn't lex...flex? I have flex installed...unless there is another version or specific version u want me to install? What version of flex?
On Apr 11, 2015 6:33 AM, Wilfred Hughes notifications@github.com wrote:
lex: not found

You need lex installed. I've added a note in the README about this.

**Comment by shanejamrock** [comment]
Isn't lex...flex? I have flex installed...unless there is another version or specific version u want me to install? What version of flex?

Date: Sat, 11 Apr 2015 04:33:34 -0700
