### ISSUE TITLE
_error not found, error?

### ISSUE THREAD

**Issue by facekapow** [Wilfred/babyc#4]
I keep getting this error. I am on OSX 10.10.3 with Xcode and the CLI Tools installed with lex, flex, and yacc, as well as clang, but I keep getting this error:

```
clang -Wall -Wextra -g -O0 -std=gnu99 -fstack-protector-all -ftrapv -o build/babyc main.c build/lex.yy.o build/y.tab.o build/syntax.o build/environment.o build/assembly.o build/stack.o build/context.o build/list.o
Undefined symbols for architecture x86_64:
  "_error", referenced from:
      _comment in lex.yy.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/babyc] Error 1
```

Any suggestions?

**Comment by Wilfred** [comment]
Hm, looking at this, I've no idea how it worked in the first place. I clearly copy-pasted the definition of `comment` from `c99.l`, but never defined `error`. Furthermore, it's worrying to use a function `void error(char *s)` when `error.h` defines `error` with a different signature.

I've push a change that should help with this, let me know.

**Comment by facekapow** [comment]
It works now! Thanks. BTW, nice little compiler here. I'm gonna fork it and play around with it. It looks promising!
